language: python
python:
  - "3.5"
  
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls

script:
  - coverage run test_rpn.py
  - coverage report

after_success:
  - coveralls